const assert=require('assert/strict');
const fs=require('fs'),path=require('path');
const api=require('./secondary_sources.js');
const read=name=>JSON.parse(fs.readFileSync(path.join(__dirname,'test_fixtures',name),'utf8'));
const row=read('howardhanna_193660_row.json'),record=read('howardhanna_193660.json');
assert.equal(api.matches(row,record),true);
assert.equal(api.fact(row,record,'sqft').value,'1488');
assert.equal(api.fact(row,record,'roof_type').value,'Asphalt roof');
assert.equal(api.fact(row,record,'lot_area_acres').unit,'acre');
assert.equal(api.photos(row,record).length,1);
assert.equal(api.matches({...row,city:'Erie'},record),false);
assert.equal(api.matches({...row,address:row.address+' Unit 2'},record),false);
assert.equal(api.matches({...row,county:'Allegheny'},record),false);
assert.equal(api.matches({...row,url:row.url+'/changed'},record),false);
assert.equal(api.matches(row,{...record,provider:'tarasa'}),false);
assert.equal(api.matches(row,{...record,source_url:record.source_url+'?mlsnumber=193660'}),false);
assert.equal(api.photos(row,{...record,photos:[{...record.photos[0],url:record.photos[0].url.replace('?d=l','?d=t')}]}).length,0);
assert.equal(api.photos(row,{...record,photos:[{...record.photos[0],source_url:record.source_url+'/wrong'}]}).length,0);
assert.equal(api.photos(row,{...record,photos:[{...record.photos[0],url:record.photos[0].url.replace('photos.prod.cirrussystem.net','evil.example')}]}).length,0);
console.log('14 Howard Hanna browser identity, fact, photo and provenance checks passed');
